name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
  MAILCHIMP_API_SERVER: ${{ secrets.MAILCHIMP_API_SERVER }}
  MAILCHIMP_AUDIENCE_ID: ${{ secrets.MAILCHIMP_AUDIENCE_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          cache: 'npm'
      - name: Install Project
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Jest Tests
        run: npm run coverage
      - name: Build
      - run: npm run build --if-present
