name: Build, Lint and Test CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install And Lint
        run: npm install && npm run lint
        env:
          CI: true
      - name: Build And Test
        run: npm run build
        env:
          CI: true
